# Generated by Django 3.2.2 on 2021-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210606_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(upload_to='images', verbose_name='Zdjęcie produktu'),
        ),
    ]
